# Generated by Django 5.0.2 on 2026-05-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='animation_strings',
            field=models.TextField(default='Fisheries & Marine Science Enthusiast|Engineering Solutions Developer|Ocean Conservation Advocate|Data Analysis Specialist|Passionate About Sustainable Fisheries', help_text='Typing animation strings separated by | (pipe character)'),
        ),
    ]
