# Generated by Django 5.0.2 on 2026-05-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(help_text='Your professional tagline/title', max_length=500)),
                ('bio_short', models.TextField(help_text='Short introduction for hero section')),
                ('bio_long', models.TextField(help_text='Detailed about section')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('projects_count', models.IntegerField(default=0)),
                ('research_count', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
